version: "3.7"

services:
  library-api:
    image: capstone-cs.eng.utah.edu:5050/pellego/apis/library-api:latest
    container_name: library-api
    restart: always
    expose:
      - 8080

  learning-modules-api:
    image: capstone-cs.eng.utah.edu:5050/pellego/apis/learning-modules:latest
    container_name: learning-modules-api
    restart: always
    expose:
      - 8081

  users-api:
    image: capstone-cs.eng.utah.edu:5050/pellego/apis/user-api:latest
    container_name: users-api
    restart: always
    expose:
      - 8082

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
